# Generated by Django 5.0.1 on 2024-02-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_appointmenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenthistory',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
