# Generated by Django 5.0.2 on 2024-02-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_appointmenthistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenthistory',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointmenthistory',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
