# Generated by Django 4.2.5 on 2023-12-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_adharcard_adhar_no_alter_adharcard_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adharcard',
            name='person',
        ),
    ]
