# Generated by Django 4.2.5 on 2023-12-10 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_adharcard_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='adharcard',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
    ]
